[package]
name = "rs-es"
version = "0.7.1"
authors = ["Ben Ashford"]
license = "Apache-2.0"
repository = "https://github.com/benashford/rs-es"
documentation = "http://benashford.github.io/rs-es/rs_es/index.html"
description = "Client for the ElasticSearch REST API"
readme = "README.md"
keywords = ["elasticsearch", "elastic"]
exclude = ["devbox/**/*", "docker-dev.yml"]

[lib]
name = "rs_es"

[features]
ssl = ["hyper/ssl"]

[dependencies]
hyper = {version = "^0.9", default-features = false}
log = "^0.3"
maplit = "^0.1"
serde = "^0.8.19"
serde_json = "^0.8.1"
serde_derive = "^0.8.19"
url = "^1.2"

[dev-dependencies]
env_logger = "^0.3"
regex = "^0.1"
