[package]
name = "rs-es"
version = "0.4.3"
authors = ["Ben Ashford"]
license = "Apache-2.0"
repository = "https://github.com/benashford/rs-es"
documentation = "http://benashford.github.io/rs-es/rs_es/index.html"
description = "Client for the ElasticSearch REST API"
readme = "README.md"
keywords = ["elasticsearch", "elastic"]
exclude = ["devbox/**/*", "docker-dev.yml"]
build = "build.rs"

[lib]
name = "rs_es"

[features]
default = ["default_without_ssl","ssl"]
nightly = ["nightly_without_ssl","ssl"]
default_without_ssl = ["serde_codegen"]
nightly_without_ssl = ["serde_macros"]
ssl = ["hyper/ssl"]

[build-dependencies]
serde_codegen = {version = "^0.7.10", optional = true}

[dependencies]
hyper = {version = "^0.9", default-features = false}
log = "^0.3"
maplit = "^0.1"
serde = "^0.7.10"
serde_json = "^0.7.1"
serde_macros = {version = "^0.7.10", optional = true}

[dev-dependencies]
env_logger = "^0.3"
regex = "^0.1"
