[package]
name = "rs-es"
version = "0.11.0"
authors = ["Ben Ashford"]
license = "Apache-2.0"
repository = "https://github.com/benashford/rs-es"
description = "Client for the ElasticSearch REST API"
readme = "README.md"
keywords = ["elasticsearch", "elastic"]
exclude = ["docker-dev.yml"]
edition = "2018"

[lib]
name = "rs_es"

[features]
default = ["ssl"]
ssl = ["hyper-openssl"]

[dependencies]
hyper = "^0.10"
hyper-openssl = { version = "^0.2", optional = true }
log = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "^1.2"

[dev-dependencies]
env_logger = "^0.4"
regex = "^0.2"
